config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts do
    resources :comments
  end

  root 'posts#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :post

	validates :title, presence: true
	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :comment, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	has_many :comments

	validates :title, presence: true
	validates :category, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :posts
   has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :get_categories, only: [:index, :show]
    
    def index
    end
    
    def show
        @posts = Post.where(category_id: params[:id]).order("created_at DESC")
        @category = Category.where(id: params[:id]).take
    end
    
    private
    def get_categories
       @categories = Category.all.order("title") 
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :get_post_and_comments, :handle_unauthorized_users, only: [:edit, :update, :destroy]
	before_action :authenticate_user!

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:comment))
		@comment.user_id = current_user.id if current_user

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
	end

	def update

		if @comment.update(params[:comment].permit(:comment))
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to post_path(@post)
	end


	private
	
	def get_post_and_comments
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])	
	end

	def handle_unauthorized_users
		
		if(@comment.user != current_user)
			redirect_to post_path(@post)
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order("created_at DESC")
		@categories = Category.all.order("title")
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = current_user.posts.build
		@categories = Category.all.order('title')
	end

	def create
		@category = Category.find_by_id(post_params[:category])
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@categories = Category.all.order('title')
	end

	def update
		
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content, :category_id)
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.haml
%h2
    Categories

#categories
    - @categories.each do |category|
        .category
            %h2= link_to category.title, category 

app/views/categories/show.html.haml
#category-title.page-title
    %h2= @category.title
.categories-dropdown
    .button.categories
        Categories
        .fa.fa-sort-desc
    .categories-list
        = link_to "All Categories", posts_path
        - @categories.each do |category|
            = link_to category.title, category

#posts
    - @posts.each do |post|
        .post
            %h2.title= link_to post.title, post
            %p.date
                published : 
                = time_ago_in_words(post.created_at)
                by
                = post.user.email

app/views/comments/_comment.html.haml
.comment.clearfix
	.profile
		%p.comment_author
			from: 
			= comment.user.username if comment.user
			%br/
			posts:
			= @post.user.posts.count
			%br/
			member since:
			%br/
			%small= @post.user.created_at.strftime("%d %b. %Y")
	.content
		%p.comment_content= comment.comment

		- if comment.user == current_user
			.buttons
				= link_to "Edit", edit_post_comment_path(comment.post, comment)
				= link_to "Delete", [comment.post, comment], method: :delete, data: {confirm: "are you sure?"}

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
	= f.input :comment
	= f.submit

app/views/comments/edit.html.haml
%h1 Edit reply
= simple_form_for([@post, @comment]) do |f|
	= f.input :comment
	= f.submit

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Rails Forum App
	= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
	%link{ href: 'http://fonts.googleapis.com/css?family=Lato:400,300,700', rel: 'stylesheet', type: 'text/css' }
	%link{ href: 'https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css', rel: 'stylesheet', type: 'text/css' }
	%link{ href: '	https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css', rel: 'stylesheet', type: 'text/css' }
	%link{ href: '//code.jquery.com/jquery-1.11.3.min.js', type: 'text/javascript' }
	
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%header.clearfix
		.container
			= link_to root_path, id: "logo" do
				%p Test

			#buttons
				-if user_signed_in?
					= link_to "New Thread", new_post_path
					= link_to "Logout", destroy_user_session_path, method: :delete
				-else
					= link_to "Sign up", new_user_registration_path
					= link_to "Sign in", new_user_session_path
					

	.container
		%p.notice= notice 
		%p.alert= alert 
	.container
		= yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
	= f.input :title
	= f.input :content
	= f.input :category_id, collection: @categories, label_method: :title, value_method: :id
	= f.submit

app/views/posts/edit.html.haml
%h1 Edit Post

= render 'form'

= link_to "Cancel", post_path

app/views/posts/index.html.haml
%h2.page-title
	All Recent Posts
.categories-dropdown
	.button.categories
		Categories
		.fa.fa-sort-desc
	.categories-list
		= link_to "All Categories", posts_path
		- @categories.each do |category|
			= link_to category.title, category
#posts
	- @posts.each do |post|
		.post
			%h2.title= link_to post.title, post
			%p.date
				published : 
				= time_ago_in_words(post.created_at)
				by
				= post.user.username
			%p.category
				category :
				= post.category.title if post.category

app/views/posts/new.html.haml
%h1 new post

= render 'form'

app/views/posts/show.html.haml
#post_content
	.comment.clearfix
		.profile
			%p.comment_author
				from: 
				= @post.user.username
				%br/
				posts:
				= @post.user.posts.count
				%br/
				member since:
				%br/
				%small= @post.user.created_at.strftime("%d %b. %Y")
		.content
			%h1= @post.title
			%p= @post.content

			%p
				%small
					post-replies: 
					= @post.comments.count
				
		
			-if @post.user == current_user
				= link_to "Edit", edit_post_path(@post), class: "button"
				= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "button"

	#comments
		= render @post.comments

		%h3 reply to thread
		= render "comments/form"